### ISSUE TITLE
Enable 5.2 compatibility in Lua 5.3

### ISSUE THREAD

**Issue by ccarrasc** [gudzpoz/luajava#192]
**Is your feature request related to a problem? Please describe.**
Lua 5.3 has a [compiler flag set to allow 5.2 compatitibilty](https://github.com/lua/lua/blob/75ea9ccbea7c4886f30da147fb67b693b2624c26/makefile#L56). I dug through the documentation and was unable to determine if excluding the flag was intentional or not. 

Currently, attempting to execute the following results in an exception (attempt to call a nil value (field 'pow')):
```
         try (var lua = new Lua53()) {
             lua.openLibraries();
             var res = lua.eval("return math.pow(2, 2)");
             return res[0].toNumber();
         }
```

**Describe the solution you'd like**
Enable `LUA_COMPAT_5_2` for lua53.

**Additional context**
I think all that is needed is to add `-DLUA_COMPAT_5_2` to `cFlags` in lua53's build.gradle. I can open a PR, but it would take me some time to figure out how to build and test the change.

**Comment by ccarrasc** [comment]
I see the build failed when merged. I can't find the stacktrace to understand the issue. I assume that it's a CI issue since the build passed prior to merge, and there is nothing on top of it. If you need help debugging the build, let me know, @gudzpoz

**Comment by gudzpoz** [comment]
@ccarrasc For the CI errors, I have rather grown accustomed to them:
- Some of them just come up regularly during the [ReactiveCircus/android-emulator-runner](https://github.com/ReactiveCircus/android-emulator-runner) step when Google makes any changes to Android images/SDK and deleting the build cache usually fixes that.
- ReactiveCircus/android-emulator-runner also has a bunch of issues that seem to be triggered a bit randomly.
- Sometimes, [`jnigen` will report failing to make dirs](https://github.com/gudzpoz/luajava/actions/runs/9906567530/job/27368740079#step:9:157), which I really have no idea about (as the source code line is guarded by [a `!libsDir.exists()` clause](https://github.com/libgdx/gdx-jnigen/blob/3031838bd6284cd1cfa0050ade874875cf4f0f4c/gdx-jnigen/src/main/java/com/badlogic/gdx/jnigen/AntScriptGenerator.java#L91)). But rerunning the step usually fixes that.

I consider most of these upstream issues, but have failed to make them reproducible enough to report them. You may look into them, but personally I won't recommend it since debugging CI-only issues is a pain (for me, at least).
Anyways, thank you again!
